// Step 3 of compatibility-check: point the library's workspace at the React Native version under
// test, changing as little as the target requires (rules in lib/swap.mjs and the README), and log
// every change. The repository root, the package's own folder and the demo app are swapped together
// so the workspace resolves one React Native version.
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, posix } from 'node:path';
import { outDir, readJson, writeJson } from './lib/config.mjs';
import { BUILD_GRADLE, gradleVersionOf, planGradleWrapper, planSdkVersions, withDistributionUrl, withSdkVersions, WRAPPER_PROPERTIES } from './lib/gradle.mjs';
import { detectDemoKind, packageManager, readInputs, repoPath } from './lib/library.mjs';
import { fail } from './lib/proc.mjs';
import { gatherSwapRegistry } from './lib/registry.mjs';
import { lineOf } from './lib/semver.mjs';
import { formatSwap, localSpec, planSwap, workspacePackageDirs } from './lib/swap.mjs';

const inputs = readInputs();
const { packageDir, demoApp } = inputs.settings;
const demoFile = `${demoApp}/package.json`;
// The root, the package under test, the demo app, and every other workspace package: a sibling
// package left on other react or react-test-renderer versions installs a second React (lib/swap.mjs).
const rootManifest = existsSync(repoPath('package.json')) ? readJson(repoPath('package.json')) : {};
const listDirs = (dir) => {
  const path = dir ? repoPath(dir) : repoPath('.');
  try {
    return readdirSync(path).filter((name) => !name.startsWith('.') && statSync(join(path, name)).isDirectory());
  } catch {
    return [];
  }
};
const workspaceFiles = workspacePackageDirs(rootManifest.workspaces, listDirs).map((dir) => `${dir}/package.json`);
const files = [...new Set(['package.json', `${packageDir}/package.json`.replace(/^\.\//, ''), demoFile, ...workspaceFiles])];

if (!existsSync(repoPath(demoFile))) fail(`The library has no demo app at ${demoFile} (demo.dir in green-packages.toml).`);
const manifests = files.filter((file) => existsSync(repoPath(file))).map((file) => ({ file, manifest: readJson(repoPath(file)) }));

const demoKind = detectDemoKind(repoPath(demoApp), manifests.find((m) => m.file === demoFile).manifest);
if (!demoKind) fail(`The demo app at ${demoApp} has neither native folders nor an expo dependency.`);

const target = inputs.reactNativeVersion;
let registry;
try {
  registry = await gatherSwapRegistry({ manifests, demoKind, target });
} catch (error) {
  fail(`Could not read the npm registry: ${error.message}`);
}

// The demo app is pointed at the checked-out package when it names a published version of it.
const library = {
  name: inputs.package,
  spec: localSpec(packageManager(repoPath(demoApp)), posix.relative(demoApp, packageDir === '.' ? '' : packageDir) || '.'),
};
const plan = planSwap({ manifests, demoFile, demoKind, target, registry, library });
// A setup failure: nothing is written and no result is recorded (README, "What is and is not recorded").
if (plan.blocked) fail(plan.blocked);
for (const { file, manifest } of plan.manifests) writeFileSync(repoPath(file), `${JSON.stringify(manifest, null, 2)}\n`);

// The Gradle wrapper follows the React Native version in every case, even when no package version
// changes: a demo app's committed wrapper can be too old for its own React Native version. A bare
// demo app's wrapper is set now; an Expo demo app's is generated by `expo prebuild`, so the Android
// check sets it right after that.
const wrapperFile = `${demoApp}/${WRAPPER_PROPERTIES}`;
const gradleUrl = registry.gradleDistributionUrl;
const gradleReason = `from @react-native-community/template for ${lineOf(target)}`;
if (!gradleUrl) {
  plan.notes = [...(plan.notes ?? []), `Gradle wrapper: no template value for ${lineOf(target)}, left as the demo app has it.`];
} else if (demoKind === 'bare' && existsSync(repoPath(wrapperFile))) {
  const current = readFileSync(repoPath(wrapperFile), 'utf8');
  const change = planGradleWrapper(current, gradleUrl);
  if (change) {
    writeFileSync(repoPath(wrapperFile), withDistributionUrl(current, change.to));
    plan.changes.push({ file: wrapperFile, name: 'Gradle', from: gradleVersionOf(change.from), to: gradleVersionOf(change.to), reason: gradleReason });
  }
} else if (demoKind === 'expo') {
  plan.changes.push({ file: wrapperFile, name: 'Gradle', from: '(generated by expo prebuild)', to: gradleVersionOf(gradleUrl), reason: `${gradleReason}, set after expo prebuild` });
}

// The Android SDK follows the React Native version the same way: the line's Android Gradle plugin
// can only find the platforms it knows, and a demo app written for a newer line asks for a newer one
// (compileSdkVersion 37 on a plugin tested up to 36 fails before anything compiles). A bare demo app's
// root build.gradle is set to the template's SDK; an Expo demo app's is generated by `expo prebuild`
// from its SDK, which already matches the line.
const buildGradleFile = `${demoApp}/${BUILD_GRADLE}`;
const sdkReason = `from @react-native-community/template for ${lineOf(target)}`;
if (!registry.sdkVersions) {
  plan.notes = [...(plan.notes ?? []), `Android SDK: no template value for ${lineOf(target)}, left as the demo app has it.`];
} else if (demoKind === 'bare' && existsSync(repoPath(buildGradleFile))) {
  const current = readFileSync(repoPath(buildGradleFile), 'utf8');
  const changes = planSdkVersions(current, registry.sdkVersions);
  if (changes.length > 0) {
    writeFileSync(repoPath(buildGradleFile), withSdkVersions(current, Object.fromEntries(changes.map((c) => [c.name, c.to]))));
    for (const { name, from, to } of changes) plan.changes.push({ file: buildGradleFile, name, from, to, reason: sdkReason });
  }
}

writeJson(join(outDir(), 'swap.json'), {
  target,
  demoKind,
  swapCase: plan.swapCase,
  fromReactNative: plan.fromReactNative,
  expoSdk: plan.expoSdk,
  keptExpo: plan.keptExpo,
  jestPreset: plan.jestPreset,
  template: plan.swapCase === 'line' ? (registry.templateVersion ?? null) : null,
  // Set by the Android check after `expo prebuild` generates an Expo demo app's wrapper.
  gradleDistributionUrl: demoKind === 'expo' ? (gradleUrl ?? null) : null,
  changes: plan.changes,
});
const text = `${demoKind} demo app at ${demoApp}\n${formatSwap(plan, target)}`;
mkdirSync(join(outDir(), 'logs'), { recursive: true });
writeFileSync(join(outDir(), 'logs', 'swap.txt'), text);
process.stdout.write(text);
